name: app1cli
version: 1.0.25
summary: Run app1 from Terminal
description: |
  This is an exaple Pascal project used for compare and do some calculate.
confinement: classic
base: core18  
parts:
  app1cli:
    plugin: dump
    source: https://github.com/lebao3105/app1cli/releases/download/1.0.25/app1cli.zip
apps:
  app1cli:
    command: app1

