# This is a basic workflow to compile app1
# with Pascal programming language.

name: Pascal 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install fpc
      - name: Install fpc
        run: brew install fpc
      # And sed
      - name: Get gnu-sed
        run: |
          brew install gnu-sed
          echo PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH" > ~/.bashrc
          source ~/.bashrc
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Compile
      - name: Compile the program (with English language resources)
        run: fpc app1.pas -Mdelphi
        working-directory: Pascal
      - name: Compile the program (with Vietnamese language resources)
        run: | 
          sed -i 's/lang_en/lang_vi/g' {app1{,_utils},maths}.pas
          fpc app1.pas -Mdelphi
        working-directory: Pascal
      # Clean the outputs
      - name: Clean
        run: rm -f *.o *.ppu app1
        working-directory: Pascal
