# This is a basic workflow to compile app1
# with Pascal programming language.

name: Pascal 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # I will run this workflow on Ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository
      - uses: actions/checkout@v3
      # Install fpc
      - name: Install fpc
        run: sudo apt install fpc gettext make
      
      # Compile
      - name: Compile the program (with gettext)
        run: make gen_mo && make build
        working-directory: Pascal
      
      - name: Compile the program (with lang_en unit included)
        run: | 
          sed 's/resource/lang_en/g' {app1{,_utils},maths}.pas
          fpc app1.pas -Fulangs
        working-directory: Pascal

      - name: Compile the program (with lang_vi unit included)
        run: |
          sed 's/lang_en/lang_vi/g' {app1{,_utils},maths}.pas
          fpc app1.pas -Fulangs
        working-directory: Pascal
      
      # Use compile_lang.sh
      - name: Another test
        run: |
          ./compile_lang.sh
          sed 's/lang_vi/resource/g' {app1{,_utils},maths}.pas
          fpc app1.pas
        working-directory: Pascal
        
      # Clean the outputs
      - name: Clean
        run: rm -f *.o *.ppu app1
        working-directory: Pascal
